-   id: scss-lint
    name: scss_lint
    description: ''
    entry: scss-lint
    language: ruby
    'types': [scss]
    args: []
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
